// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrrfggtrkoragwwameol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycmZnZ3Rya29yYWd3d2FtZW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTE5NTQsImV4cCI6MjA2Njg4Nzk1NH0.cWKJ5hIu2pPHLGJCN8_8bF6JOXhalVAksr2bMUJ2VPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});